### ISSUE TITLE
Toliss fire extinguishers not working

### ISSUE THREAD

**Issue by justinsnapp** [sharedflight/issues-tracker#13]
`Trigger AirbusFBW/FireExOHPArray[0:8]`

Looks like this should be changed to:

`Trigger AirbusFBW/FireExOHPArray[0:8] @ 0` 

For both the 319 and 321 (and 340)....

**Comment by tailwest** [comment]
Changed
Trigger AirbusFBW/FireExOHPArray[0:8] @ 0
